### ISSUE TITLE
Position of player

### ISSUE THREAD

**Issue by fiedler-eng** [codyphobe/among-us-protocol#30]
Is it possible to specify the "Target Position" in CustomNetworkTransform more precise (does the position represent the upper left corner of the player sprite or the center of the player)?

**Comment by Sanae6** [comment]
The position specified by a CustomNetworkTransform is the center of the player's sprite. If you're wondering, this doesn't correlate to the player's true position, the player sprite's center plus the offset of the collider from the player's center.
![playerpos](https://user-images.githubusercontent.com/32604996/114052372-3c812d80-984b-11eb-812f-a39ada7ea359.png)
The true position is used for several physics calculations and sound occlusion.
