### ISSUE TITLE
GameData seems to be wrong

### ISSUE THREAD

**Issue by fiedler-eng** [codyphobe/among-us-protocol#31]
In my opinion, InnerNetObject/GamaData object doesn't contain the Players Length and the Player ID. The Data message (in GameData message) contains a Hazel Message for each player (in case of NetID is the id of the game, not of the player object). The Tag of the Hazel Message is the PlayerID.

**Comment by edqx** [comment]
I don't think so. Data should go directly to the component to deserialize.
Also dnspy disagrees with you.
![image](https://user-images.githubusercontent.com/60631511/114312882-2cd44400-9aec-11eb-992d-3c3ad407261f.png)

**Comment by edqx** [comment]
I've deleted my last comment as it appears I can't read, you're right in that it reads a HazelMessage. But really, a pull request wouldn't hurt.

**Comment by codyphobe** [comment]
> In my opinion, InnerNetObject/GamaData object doesn't contain the Players Length and the Player ID. The Data message (in GameData message) contains a Hazel Message for each player (in case of NetID is the id of the game, not of the player object). The Tag of the Hazel Message is the PlayerID.

You're right; this was one of the changes along with the Airship update that I didn't have time to fix but will do now.

EDIT: Fixed in 6fe26c74dd894e2abaa86a040c8391e7f1022bd8
